name: Updater (WIP)


on:
  push:
    branches:
      - main

jobs:
  deploy:

    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - name: checkout main
      uses: actions/checkout@v1
      with:
        submodules: true

    - name: Setup Hugo
      uses: peaceiris/actions-hugo@v2
      with:
        hugo-version: 'latest'
        extended: true
    - name: Build
      run: hugo --minify

    - name: Hugo Deploy GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      if: ${{ github.ref == 'refs/heads/main' }}
      with:
        github_token: ${{ secrets.GITHUB_ATOKENTOKEN }}
        publish_dir: ./public
