name: Updater (WIP)


on:
  push:
    branches:
      - main

jobs:
  deploy:

    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - name: checkout main
      uses: actions/checkout@v1
      with:
        submodules: true

    - name: Setup Hugo
      uses: peaceiris/actions-hugo@v2
      with:
        hugo-version: 'latest'
        extended: true
    - name: Build
      run: hugo --minify

    - name: Hugo Deploy GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
        publish_dir: ./public
        publish_branch: main
        external_repository: alexander-belikov/alexander-belikov.github.io
        allow_empty_commit: true
