name: Updater

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Deploy
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v1
        with:
          submodules: true
      - name: Deploy the site
        uses: benmatselby/hugo-deploy-gh-pages@master
        env:
          HUGO_VERSION: 0.109.0
          TARGET_REPO: alexander-belikov/alexander-belikov.github.io
          TARGET_BRANCH: main
          TOKEN: ${{ secrets.ATOKEN }}
          HUGO_ARGS: '-t academic'
          CNAME: alexander-belikov.github.io
